CREATE TABLE worker (
    id INT PRIMARY KEY,
    NAME VARCHAR(1000) NOT NULL,
    CHECK (NAME LIKE '__%'),
    BIRTHDAY DATE, 
    CHECK (BIRTHDAY >= '1901.01.01'),
    LEVEL VARCHAR(10),
    CHECK(LEVEL = 'Trainee' 
    OR LEVEL = 'Junior' 
    OR LEVEL = 'Middle' 
    OR LEVEL = 'Senior'),
    SALARY INT,
    CHECK (SALARY >=100 AND SALARY <=100000)
);


CREATE TABLE client (
    id INT PRIMARY KEY,
    NAME VARCHAR(1000) NOT NULL,
    CHECK (NAME LIKE '__%')
);
 
 

CREATE TABLE project (
    ID INT PRIMARY KEY,
    CLIENT_ID INT,
    FOREIGN KEY(CLIENT_ID) REFERENCES client1(id) ON DELETE CASCADE,
    START_DATE DATE,
    FINISH_DATE DATE
);

CREATE TABLE project_worker (
    PROJECT_ID INT,
    WORKER_ID INT,
    PRIMARY KEY(PROJECT_ID,WORKER_ID),
    FOREIGN KEY(PROJECT_ID) REFERENCES project1(ID), 
    FOREIGN KEY(WORKER_ID) REFERENCES worker1(id)
);
